---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: 了解NetApp Console的功能和数据服务的最新变化。 
---
= NetApp Console中的最新更改
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解NetApp Console的功能和数据服务的最新变化。要查看完整的发布历史记录，请访问link:release-notes-index.html["全套发行说明"]针对每项单独的服务。



== 管理功能

本节介绍与NetApp Console管理功能相关的新功能：组织、识别和访问、控制台代理、云提供商凭据等。



== 警报



== 适用于ONTAP 的Amazon FSx



== Amazon S3 存储



== Azure Blob 存储



== Azure NetApp Files



== 备份和恢复



== 数据分类



== Cloud Volumes ONTAP



== 复制和同步



== 数字顾问



== Licenses and subscriptions



=== 2025年10月6日



==== BlueXP现在是NetApp Console

NetApp Console建立在增强和重组的BlueXP基础之上，可在企业级内部和云环境中集中管理NetApp存储和NetApp Data Services，提供实时洞察、更快的工作流程和简化的管理，并且高度安全且合规。

有关更改的详细信息，请参阅link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp Console发行说明"]。



=== 2025年3月10日



==== 可以删除订阅

如果您已取消订阅，现在可以从数字钱包中删除订阅。



==== 查看 Marketplace 订阅的已消耗容量

查看 PAYGO 订阅时，您现在可以查看订阅的已消耗容量。



=== 2025年2月10日

BlueXP digital wallet经过重新设计，易于使用，现在提供额外的订阅和许可证管理。



==== 新的概览仪表板

数字钱包主页具有更新的NetApp许可证和 Marketplace 订阅仪表板，可以深入了解特定服务、许可证类型和所需的操作。



==== 配置凭证订阅

BlueXP digital wallet现在允许您配置对提供商凭证的订阅。通常，您在首次订阅 Marketplace 订阅或年度合同时执行此操作。以前，只能在“凭据”页面上更改订阅的凭据。



==== 将订阅与组织关联

您现在可以直接从数字钱包更新与订阅关联的组织。



==== 管理 Cloud Volume ONTAP许可证

您现在可以通过主页或“直接许可证”选项卡管理Cloud Volumes ONTAP许可证。使用“市场订阅”选项卡查看您的订阅信息。



=== 2024年3月5日



==== BlueXP disaster recovery

BlueXP digital wallet现在使您能够管理BlueXP disaster recovery的许可证。您可以添加许可证、更新许可证以及查看有关许可容量的详细信息。

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["了解如何管理BlueXP数据服务的许可证"]



=== 2023年7月30日



==== 使用情况报告增强功能

Cloud Volumes ONTAP使用情况报告现已有几项改进：

* TiB 单位现在包含在列名中。
* 现在包含一个用于序列号的新_node(s)_字段。
* 存储虚拟机使用情况报告下现在包含一个新的“工作负载类型”列。
* 工作环境名称现在包含在存储虚拟机和卷使用情况报告中。
* 卷类型_file_现在标记为_Primary (Read/Write)_。
* 卷类型 _secondary_ 现在标记为 _Secondary (DP)_。


有关使用情况报告的更多信息，请参阅 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["下载使用情况报告"]。



== 灾难恢复



== E系列系统



== 生命周期规划



== 边缘缓存

边缘缓存服务于 2024 年 8 月 7 日被删除。



== Google Cloud NetApp Volumes



== Google Cloud Storage



== Keystone



== Kubernetes

2024 年 8 月 7 日，对发现和管理 Kubernetes 集群的支持被取消。



== 迁移报告

迁移报告服务已于 2024 年 8 月 7 日移除。



== 本地ONTAP集群



== 运营弹性

运营弹性功能已于 2025 年 8 月 22 日被移除。



== 勒索软件抵御能力



== 修复

补救服务已于 2024 年 4 月 22 日删除。



== 复制



== 软件更新



== StorageGRID



== 云层



=== 2025年10月6日



==== BlueXP tiering现已更名NetApp Cloud Tiering

BlueXP tiering已重命名为NetApp Cloud Tiering。



==== BlueXP现在是NetApp Console

NetApp Console建立在增强和重组的BlueXP基础之上，可在企业级内部和云环境中集中管理NetApp存储和NetApp Data Services，提供实时洞察、更快的工作流程和简化的管理，并且高度安全且合规。

有关更改的详细信息，请参阅link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp Console发行说明"]。



=== 2023年8月9日



==== 使用自定义前缀作为存储桶名称

过去，定义存储桶名称时需要使用默认的“fabric-pool”前缀，例如 _fabric-pool-bucket1_。现在您可以在命名存储桶时使用自定义前缀。仅当将数据分层到 Amazon S3 时此功能才可用。 https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["了解更多"] 。



==== 在所有BlueXP连接器中搜索集群

如果您使用多个连接器来管理环境中的所有存储系统，则您想要实施分层的某些集群可能位于不同的连接器中。如果您不确定哪个连接器正在管理某个集群，您可以使用 Cloud Tiering 在所有连接器中进行搜索。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["了解更多"] 。



=== 2023年7月4日



==== 调整带宽以传输非活动数据

当您激活 Cloud Tiering 时， ONTAP可以使用无限量的网络带宽将集群中卷中的非活动数据传输到对象存储。如果您注意到分层流量影响了正常的用户工作负载，您可以限制传输期间可使用的带宽量。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["了解更多"] 。



==== 通知中心显示的分层事件

当集群分层的冷数据少于 20%（包括未分层任何数据的集群）时，分层事件“将集群 <name> 中的其他数据分层到对象存储以提高存储效率”现在会作为通知出现。

此通知是一项“建议”，旨在帮助您提高系统效率并节省存储成本。它提供了一个链接 https://www.netapp.com/data-services/tiering/tco-calculator/["Cloud Tiering 总拥有成本和节省计算器"^]帮助您计算成本节省。



== 卷缓存



== 工作负载工厂



=== 2025年10月6日



==== BlueXP workload factory现为NetApp Workload Factory

BlueXP已重命名并重新设计，以更好地反映其在管理数据基础设施中的作用。因此， BlueXP workload factory已重命名为NetApp Workload Factory。



==== Ask Me 与 MCP 集成

Workload Factory 的 AI 助手 Ask Me 与模型上下文协议 (MCP) 集成。使用 MCP，Ask Me 可以安全地与外部环境交互并查询 API 工具，以提供适合您特定存储环境的响应。



=== 2025年10月5日



==== 存储的新通知

NetApp Workload Factory通知服务包括针对存储架构问题的通知。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["NetApp Workload Factory通知"]



=== 2025年9月9日



==== 存储的新通知

BlueXP workload factory通知服务包括存储自动容量管理通知。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["BlueXP workload factory的通知"]
