= 已添加对将卷备份到 S3 配置的ONTAP系统上的存储桶的支持
:allow-uri-read: 


[IMPORTANT]
====
* 由于重要的安全增强，您的连接器现在需要对其他端点进行出站互联网访问，以便管理公共云环境中的备份和恢复资源。如果此端点尚未添加到防火墙的“允许”列表中，您将在 UI 中看到有关“服务不可用”或“无法确定服务状态”的错误：
+
\ https://netapp-cloud-account.auth0.com

* 当您使用“CVO Professional”包时，现在需要备份和恢复 PAYGO 订阅，该包使您能够捆绑Cloud Volumes ONTAP和BlueXP backup and recovery。过去这并不是必需的。符合条件的Cloud Volumes ONTAP系统的备份和恢复订阅不会产生任何费用，但在任何新卷上配置备份时需要付费。


====


=== 已添加对将卷备份到 S3 配置的ONTAP系统上的存储桶的支持

现在，您可以使用已配置为简单存储服务 (S3) 的ONTAP系统将卷备份到对象存储。本地ONTAP系统和Cloud Volumes ONTAP系统均支持此功能。此配置在云部署和没有互联网访问的本地位置（“私有”模式部署）中受支持。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["了解更多"] 。



=== 现在，您可以将受保护卷中的现有快照包含在备份文件中

过去，您可以将初始备份文件中读写卷的现有 Snapshot 副本包含到对象存储中（而不是从最新的 Snapshot 副本开始）。只读卷（数据保护卷）的现有 Snapshot 副本未包含在备份文件中。现在您可以选择将较旧的 Snapshot 副本包含在“DP”卷的备份文件中。

备份向导会在备份步骤结束时显示一个提示，您可以在其中选择这些“现有快照”。



=== BlueXP backup and recovery不再支持将来添加的卷的自动备份

以前，您可以在备份向导中选中一个框，将选定的备份策略应用于添加到集群的所有未来卷。根据用户反馈和此功能的使用不足，此功能已被删除。您需要手动为添加到集群的任何新卷启用备份。



=== 作业监控页面已更新新功能

作业监控页面现在提供更多与 3-2-1 备份策略相关的信息。该服务还提供与备份策略相关的额外警报通知。

“备份生命周期”类型过滤器已重命名为“保留”。使用此过滤器来跟踪备份生命周期并识别所有备份副本的到期时间。  “保留”作业类型捕获在受BlueXP backup and recovery保护的卷上启动的所有快照删除作业。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["了解有关更新的 Job Monitor 的更多信息"] 。
